### ISSUE TITLE
Question: DB operations in "main file" 

### ISSUE THREAD

**Issue by nirre7** [NathanaelA/nativescript-sqlite-example#1]
Hi.

Thanks for this nice piece of code ;)

I have a fairly common usecase and I'm struggling a bit with how to solve it.
I have an app with a login screen. 
If a user has logged in I don't want to show the login screen, I want to open a list page. 
If possible, I want to be able to decide when the app loads, i.e my "main" file should decide application.mainModule dependent on. 

My issue is that I get an error that context is not available (android) and I can't check if db exists: (line 754) var dbName = appModule.android.context.getDatabasePath(name).getAbsolutePath(); .

My workaround atm is to check if db exists + user exists within the login screen (when loaded is called) and then "redirect" the user to the list page.

Can you advice on a better solution or is it a limitation?

Thanks in advance
Niclas

**Comment by NathanaelA** [comment]
In my app; I actually use the first screen as a loading screen. Then I decide if they are logged in and switch to the next "proper" screen.    

I actually do have a fix for this; as I ran into this same issue in my LiveEdit product.   I'll copy the code over to the sqlite code.

**Comment by NathanaelA** [comment]
I just pushed v1.06 that should fix this.  :grinning:   Please confirm so that I can close this issue.

**Comment by nirre7** [comment]
Great! Quick turnaround!
Just realised I posted this in the wrong repo :(

* It works in my "main" file now and in my "loaded" function
* Sqlite.exists does not work in my workaround though (which I have in my loaded function), i get this:
*TypeError: this._getContext is not a function
File: "/data/data/org.nativescript.seeqrightdevice/files/app/tns_modules/nativescript-sqlite/sqlite.js, line: 770, column: 22
Frame: function:'Database.exists', file:'/data/data/org.nativescript.seeqrightdevice/files/app/tns_modules/nativescript-sqlite/sqlite.js', line: 770, column: 23
	Frame: function:'doesDbExist', file:'/data/data/org.nativescript.seeqrightdevice/files/app/service/db/dbService.js', line: 4, column: 19
	Frame: function:'', file:'/data/data/org.nativescript.seeqrightdevice/files/app/app.js', line: 5, column: 16*

**Comment by NathanaelA** [comment]
LOL, doesn't that figure.   I knew I should have tested it before pushing.   To many things on my plate today.   I'll try and get this fixed shortly...

**Comment by nirre7** [comment]
No worries, thanks for getting it sorted though ;)

**Comment by NathanaelA** [comment]
Ok, I pushed the fix.  Sorry about that.  :grinning:   Let me know if you are good to go.
