### ISSUE TITLE
"plugins" without "s" , And  where is db.close()?

### ISSUE THREAD

**Issue by mourahi** [NathanaelA/nativescript-sqlite-example#2]
1/ In your Readme file : 

why you add "s" to "plugin" ?

`tns plugins add nativescript-sqlite
`

2/ where is db.close() in your code ! , we must close db ?

Thanks.

**Comment by NathanaelA** [comment]
1. Thanks for the Typo catch; I've fixed it on Github...
2. I never added a db.close; since I didn't bother catching the app-close event.  This was more of a demo to show how to use it to access sqlite.   But you are probably right; I should probably add a close to the demo.
