### ISSUE TITLE
Application throwing an exception

### ISSUE THREAD

**Issue by DewaldDeJager** [NathanaelA/nativescript-sqlite-example#4]
I just cloned the repo and followed the instructions. The error is quite strange as 'app.js' is the default. There is no console output. See the device output below:

```
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Fail to load module: /data/data/org.nativescript.nativescriptsqliteexample/files/app/app.js

TypeError: Cannot read property 'CompleteCallback' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'/data/data/org.nativescript.nativescriptsqliteexample/files/app/tns_modules/http/http-request.js', line: 10, column: 41
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.nativescriptsqliteexample/files/app/tns_modules/http/http.js', line: 1, column: 79
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.nativescriptsqliteexample/files/app/tns_modules/xhr/xhr.js', line: 1, column: 72
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.nativescriptsqliteexample/files/app/tns_m
```

My setup is as follows:
Node.js: 5.3.0
NativeScript CLI: 2.1.1
tns-core-modules: 1.4.0
nativescript-sqlite: 1.0.10

I am running the application in an Android 6.0.0 (API 23) Genymotion emulator.

Is the issue perhaps that the plugin supports only Nativescript CLI versions up to 1.X? If so, will there be an update for Nativescript 2 or do you know of any alternatives for persisting data other than application settings?

**Comment by DewaldDeJager** [comment]
Okay, I have managed to get it to a running state, at least. I did the following:

- `tns create sqliteTest`
- `tns platform add android`
- 'tns plugin add nativescript-sqlite`
- Copy over the main-page.xml, main-page.js, app.css and name_db.sqlite from the example app's "app" directory to the new app

The app now runs fine on my system with the configuration stated above. Only clear difference is the difference in app.js, but I tested both in the newly created app and it works fine. I hope this is of some help to you. It certainly is to me as I was about to resort to storing JSON documents in the application document directory :P

Thanks for the great plugin!

**Comment by NathanaelA** [comment]
Awesome I'm glad it is now working for you.  Your issue actually was caused by you having a mismatch in NativeScript versions.   The CLI, Core, and plugins all need to be the same base version.  You can't run tns-core-modules 1.4 and tns-android 2.x   (See: http://fluentreports.com/blog/?p=323)
