### ISSUE TITLE
Cannot read property "CompleteCallback" of undefined

### ISSUE THREAD

**Issue by rLoka** [NathanaelA/nativescript-sqlite-example#5]
![screenshot_1477188756](https://cloud.githubusercontent.com/assets/9071942/19623729/f37f97d4-98d6-11e6-9b2c-86f13f7a6857.png)

Did not mess up with the app.

**Comment by NathanaelA** [comment]
This error message clearly has the error caused by http-request; this default app does not use or include any http/fetch/xhr code at all.     Whatever changes that you added to it are what are crashing...

**Comment by rLoka** [comment]
Thanks for quick response! Well, this has to be really strange behavior then, because I cloned the git repo, built the project with `tns buid android ` and tried to run it in emulator with `tns run android`... no changes were made .. could id be due to me having newer version of Nativescript?

Anyway, here is the full crash log from android device [http://pastebin.com/Yk5FXeE9](http://pastebin.com/Yk5FXeE9)

**Comment by NathanaelA** [comment]
Hmm, that seems very strange; that stack trace -- can you do a `tns info`?

**Comment by rLoka** [comment]
Hey .. I `run tns` info and figured I have old `tns-core-modules (1.4.0)` ..then I updated to the newest `(2.3.0) `with `npm install tns-core-modules@latest --save
` and had to install nativescript-sqlite again with `tns plugin add nativescript-sqlite` .. now everything works as expected.
